version: 2.1

jobs:
  client_testing:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: '20.10.11'
      - run:
          command: docker build -t gauravsharma/client-test -f ./client-typescript/Dockerfile.dev ./client-typescript/
          name: building the client for testing
      - run:
          command: docker run gauravsharma/client-test npm test
          name: run the client tests

  build_and_push_images:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: '20.10.11'
      - run:
          command: docker build -t gauravsharma/fibo-multi-client ./client-typescript
          name: building the production docker image for client
      - run:
          command: docker build -t gauravsharma/fibo-multi-worker ./worker
          name: building the production docker image for worker
      - run:
          command: docker build -t gauravsharma/fibo-multi-server ./server
          name: building the production docker image for server
      - run:
          command: docker build -t gauravsharma/fibo-multi-nginx ./nginx
          name: building the production docker image for nginx
      - run:
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          name: login to docker hub

      - run:
          command: |
            docker push gauravsharma/fibo-multi-client
            docker push gauravsharma/fibo-multi-worker
            docker push gauravsharma/fibo-multi-server
            docker push gauravsharma/fibo-multi-nginx

workflows:
  version: 2
  testing:
    jobs:
      - client_testing
      - build_and_push_images
